pom.xml
src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionSpawn.java

Fix: NPE on digits or invalid minecart types
Enhancement: Prevent 0 length and other invalid trains with useful error messages
This fix allows spawner signs with digits in them to work without NPE and presents more useful warnings and error messages to the player when wrong syntax is used in specifying the minecarts for a train.
Example: "2m"
Before: NPE
After: Works as intended
Example: "z"
Before: NPE
After: Message that minecart type "z" is invalid and sign is not created
Example: "0m"
Before: NPE (and if NPE was fixed, sign could be created)
After: Error that train has no valid minecarts and sign is not created
Example: "0h2m"
Before: NPE (and if NPE was fixed, sign could be created)
After: Sign is still created but with warning that there are 0 carts of type "h" in the train

Fix hasCartPerms 

---

src/main/java/com/bergerkiller/bukkit/tc/TrainCarts.java
src/main/java/com/bergerkiller/bukkit/tc/events/SignActionEvent.java
src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionMode.java

Going from 1.7 to 1.8.7 all of the signs that previously started with "[train]" or "[!train]" got converted to just "train" or "!train" -- the [ ] were stripped off. (Probably related to the new JSON support because [ ] is a JSON array.)
[ ] that are added in 1.8.7 are not stripped off. These get encoded differently now.
This patch adds a new config option called "parseOldSigns" for people (like me) with hundreds of signs created in 1.7 that no longer have any effect in 1.8. If parseOldSigns == true, the first line of any sign starting with a recognized TrainCarts pattern ("train", "cart", "t ", ...) will be updated. This allows TrainCarts to recognize the sign, and as a bonus, when the chunk is loaded the sign is updated!
This option defaults to false.
I confess this is a hack and not …

Add and implement parseOldSigns option for signs from Minecraft <= 1.7

---

pom.xml
src/main/java/com/bergerkiller/bukkit/tc/CollisionMode.java
src/main/java/com/bergerkiller/bukkit/tc/TCListener.java
src/main/java/com/bergerkiller/bukkit/tc/commands/TrainCommands.java
src/main/java/com/bergerkiller/bukkit/tc/properties/CollisionConfig.java
src/main/java/com/bergerkiller/bukkit/tc/properties/TrainProperties.java
src/main/java/com/bergerkiller/bukkit/tc/properties/TrainPropertiesStore.java
src/main/java/com/bergerkiller/bukkit/tc/statements/StatementProperty.java
src/main/java/plugin.yml

*NOTE* This requires my corresponding updates to BKCommonLib to work correctly!!!
Enhances TrainCarts to specify different actions for these mob types:
- Categories on Minecraft wiki: passive, neutral, hostile, tameable, utility, boss
- Categories previously in BKCommonLib: animal, monster, NPC
- New categories added to BKCommonLib: pets (tamed animals), jockeys, killer bunnies
Previously there was just 1 category, "mob". Now you can specify, for example, that the train will damage hostile mobs, pick up passive mobs, and kill neutral mobs.
Also added new action types, DAMAGE and DAMAGENODROPS, which damages an entity proportional to the energy of the cart that hit it, and pushes it aside. (Faster carts do more damage and the damage amount is configurable.)
All collision categories are now …

Change collision logic to use many new categories

---

pom.xml
src/main/java/com/bergerkiller/bukkit/tc/CollisionMode.java
src/main/java/com/bergerkiller/bukkit/tc/properties/TrainProperties.java

Improved logic:
- Ignore (cancel) collisions with spectator mode
- Don't kill or damage players in creative - push them aside
- Determine whether player is pushing minecart or minecart is running player over. If player is pushing minecart (which is tracked as a collision), set collision mode for this interaction to default, so player can push the cart. If the minecart is running the player over, use the configured player collision mode.
Probably solves https://github.com/bergerhealer/TrainCarts/issues/13 and https://github.com/bergerhealer/TrainCarts/issues/12

Allow pushing of minecarts/trains

---

src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionLauncher.java

If the speed of a launcher sign starts with + or -, it is relative.
The speed will be added to the current speed of the train.
If the train is going at 0.4 blocks/tick and the launcher speed is +0.2 blocks/tick, the train will be accelerated to 0.6 blocks/tick.
Closes #94

Relative launcher speed

---

src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionWait.java

If the second line of a waiter is followed by a sign type, the distance to it will be calculated.
Example:
```
[+train]
waiter waiter
```
When a train passes the sign, the distance to the next waiter is calculated and stored on the sign.
This allows you to create working block systems.
Closes #79

Calculate waiter distance

---

pom.xml
src/main/java/com/bergerkiller/bukkit/tc/Permission.java
src/main/java/com/bergerkiller/bukkit/tc/commands/GlobalCommands.java
src/main/java/plugin.yml

The command `/train issue` generates a link to create a new issue in the issue tracker.
The version fields will be filled automatically.
This also appends the Jenkins build number (if it exists) to the version: `1.12-v1-SNAPSHOT-#49`

Add /train issue

---

src/main/java/com/bergerkiller/bukkit/tc/attachments/ui/menus/GeneralMenu.java

Adds a button which duplicates an attachment node (including children).
| Before | After |
| --- | --- |
| ![Before](https://i.imgur.com/TXSusoc.png) | ![After](https://i.imgur.com/xfidYI3.png) |

Add button to duplicate attachment node

---

src/main/java/com/bergerkiller/bukkit/tc/TrainCarts.java
src/main/java/com/bergerkiller/bukkit/tc/commands/GlobalCommands.java
src/main/java/com/bergerkiller/bukkit/tc/commands/TrainCommands.java
src/main/java/com/bergerkiller/bukkit/tc/properties/SavedTrainPropertiesStore.java

Building upon the popular new feature to save trains created with the attachment editor to `savedTrainProperties.yml`, I propose a system I call `savedTrainModules`, a paradigm for managing multiple hot-reloadable `SavedTrainPropertiesStore`s. This allows for saved trains to be easily shared across servers (useful for those managing multi-server networks) and easily edited in text editors, as well as easily compartmentalizing saved trains into logical collections, or modules.
On startup, a new folder is created in the plugin's data folder, `savedTrainModules`. To save a train to this folder instead of the default `savedTrainProperties.yml`, run the command `/train save <name> <module>`. This will save your selected train to `savedTrainModules/<module>.yml` (and it will create the module …

Saved Train Modules

---

src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionLauncher.java

Fixed a bug where remote controlled launcher signs only cared about forwards and backwards launching--it now supports all directions

Added proper direction parsing to remote controlled launching

---

src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionAnnounce.java

Previously, the announce sign would pick one player arbitrarily inside of each member to announce to. I've fixed it so that it targets all players returned by `member.getEntity().getPlayerPassengers()`

Fixed annouce sign to announce to all passengers

---

src/main/java/com/bergerkiller/bukkit/tc/Station.java

Adds configurable launch speeds to station signs. `max` is a shortcut for the maximum speed of the train. Defaults to the value specified in the TrainCarts config.

Add launch speed to station sign

---

src/main/java/com/bergerkiller/bukkit/tc/commands/GlobalCommands.java

Sets the map color of the attachment editor item to red.

Color the attachment editor item

---

src/main/java/com/bergerkiller/bukkit/tc/attachments/ui/item/MapWidgetItemVariantList.java

Makes items like skulls and banners keep all of their metadata when dropped into the attachment editor. Items with multiple variants (potions, enchanted books) are not affected.

Preserve the metadata of attachment items

---

pom.xml

Javadoc was generating `errors` that concluded in unneeded failed builds. Disabling this level of logging made the `errors` appear as `warnings` in the log and the build to succeed.

Fix javadoc error

---

src/main/java/com/bergerkiller/bukkit/tc/attachments/ui/menus/AppearanceMenu.java

If you look closely, you'll notice that the attachment editor menu has been slightly offset to the left this whole time! This PR shifts it two pixels to the right to center it.
Look very closely at this image, and notice how it's slightly closer to the left side than it is to the right! We simply can't live like this anymore.

Centered appearance menu tabView (shifted x coord)

---

pom.xml
src/main/java/com/bergerkiller/bukkit/tc/TrainCarts.java
src/main/java/com/bergerkiller/bukkit/tc/attachments/control/CartAttachmentSeat.java
src/main/java/com/bergerkiller/bukkit/tc/attachments/control/seat/FirstPersonDefault.java

Seats use [SmoothCoasters](https://github.com/56738/SmoothCoasters) to control the player camera rotation if the mod is installed on the client and the Lock Rotation seat property is enabled.
[Installation](https://github.com/56738/SmoothCoasters/wiki/Installation)

Add SmoothCoasters support

---

src/main/java/com/bergerkiller/bukkit/tc/TCListener.java

**This PR should NOT be merged before https://github.com/bergerhealer/BKCommonLib/pull/100 was, as it depends on a new method added in that PR!**
This replaces the `below.getType() == Material.AIR` with `Util.ISAIR.get(below)` since 1.13 introduced `CAVE_AIR` and `VOID_AIR`, making the old check not work for 2 third of all possible checks.
Until this PR is merged would an alternative be to just replace the air blocks using WorldEdit and `//set air`

Use ISAIR Util method.

---

src/main/java/com/bergerkiller/bukkit/tc/TCListener.java

Changes `placedBlock.getType() != Material.AIR` to `!MaterialUtil.ISAIR.get(placedBlock)` since 1.13 added new Air types for caves and the void, which made the old check unreliable.

Fix upside-down rails on 1.13+

---

src/main/java/com/bergerkiller/bukkit/tc/commands/GlobalCommands.java

This updates the `/train issue` command to use the improved ChatText class of BKCommonLib for basic JSON text.
I decided to also add the feature request template as a clickable option. The (very basic) tests I made where successful and no issues or errors showed up.

Update /train issue command

---

src/main/java/com/bergerkiller/bukkit/tc/attachments/ui/item/CustomModelDataSelector.java

Fixes `/train menu set value` output as shown below

Fix ModelData property name not matching tooltip display

---

pom.xml

Maven 3.8.1+ refuses to connect to HTTP repositories. This PR changes all HTTP to HTTPS, or uses alternative repository.
For reference, see: https://nvd.nist.gov/vuln/detail/CVE-2021-26291

Change HTTP repositories to HTTPS counterparts

---

src/main/java/com/bergerkiller/bukkit/tc/events/MissingPathConnectionEvent.java
src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionSwitcher.java

This Event fires if a train reaches a switcher-sign with a set destination which couldn't be reached.
It exposes the involved MinecartGroup, PathNode and destination.

Added Event: MissingPathConnectionEvent

---

pom.xml
src/main/java/com/bergerkiller/bukkit/tc/TCConfig.java
src/main/java/com/bergerkiller/bukkit/tc/attachments/control/seat/FirstPersonDefault.java

CAMERA mode rotates the camera without changing the yaw/pitch of the player. This causes unfixable bugs like broken nametag and particle rendering and causes problems when right-clicking things (since you're not actually looking at them).
PLAYER mode rotates the player: The client changes its own yaw/pitch according to the camera rotation. This fixes the bugs caused by camera mode.
This changes the default from CAMERA to the new PLAYER mode. The mode can be changed back in the config if it causes problems (anti-cheat plugins might not like how players rotate their head).

Make SmoothCoasters rotation mode configurable

---

pom.xml
src/main/java/com/bergerkiller/bukkit/tc/attachments/control/seat/FirstPersonViewDefault.java

Removes support for older versions of the mod. The latest version contains important fixes and has been backported to 1.16.5, 1.17.1 and 1.18.2 in addition to 1.19.

Update SmoothCoasters support

---

src/main/java/com/bergerkiller/bukkit/tc/attachments/api/AttachmentInternalState.java
src/main/java/com/bergerkiller/bukkit/tc/attachments/api/AttachmentManager.java
src/main/java/com/bergerkiller/bukkit/tc/attachments/control/CartAttachment.java
src/main/java/com/bergerkiller/bukkit/tc/attachments/control/CartAttachmentEntity.java
src/main/java/com/bergerkiller/bukkit/tc/controller/components/AttachmentControllerMember.java

Fixes some issues which prevent using a custom AttachmentManager:
* Add getViewers to AttachmentManager so other manager implementations can provide viewers too
* Make sure the manager is a controller (hasController) before casting

Remove some assumptions about the type of the attachment controller

---

src/main/java/com/bergerkiller/bukkit/tc/Permission.java
src/main/java/com/bergerkiller/bukkit/tc/signactions/SignAction.java
src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionTitle.java

Minecraft has the `sendTitle` feature, where a title can be display on the player's screen. I've added a new sign to support this feature.
Configuration values for title fade in, stay, fade out are all optional values, but can be provided on the title line for additional configuration.
Example syntax:
```
[train]
title 10 70 10
foo
bar
```
Follow up review from #479

feat: add title action sign

---

README.md
src/main/java/com/bergerkiller/bukkit/tc/properties/standard/type/CollisionMobCategory.java
src/main/java/com/bergerkiller/bukkit/tc/utils/SignBuildOptions.java

The Minecraft Fandom/Gamepedia wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.

Update Minecraft wiki links to new domain
